[theme]
base = "dark"
primaryColor = "#00f5ff"
backgroundColor = "#06060f"
secondaryBackgroundColor = "#10101f"
textColor = "#e8ebff"

[server]
headless = true

[browser]
gatherUsageStats = false

[client]
toolbarMode = "minimal"
